stages:
  - download_html
  - convert_page_to_epub
  - convert_epub_to_mobi
  - send_email_to_kindle

variables:
  SITE_PROTOCOL: https
  SITE_TO_READ_LATER: https://az.id.au/ops/claude-the-laptop/

downloadHtml:
  image: alpine:latest
  stage: download_html
  only:
    - web
  script:
    - apk add wget
    - mkdir public
    - cd public
    - wget -E -H -k -p --content-on-error --restrict-file-names=nocontrol $SITE_TO_READ_LATER || true
  artifacts:
    paths:
      - public

convertPageToEpub:
  image:
    name: pandoc/core:latest
    entrypoint: ["/bin/sh", "-c"]
  stage: convert_page_to_epub
  only:
    - web
  script:
    - mkdir /epub
    - cd public
    - echo `echo $SITE_TO_READ_LATER | sed 's/^https:\/\///' | sed 's/$/.html/' | sed 's/\/.html$/\/index.html/' | sed 's/\/[^/]*.html$//'`
    - echo `echo $SITE_TO_READ_LATER | sed 's/^https:\/\///' | sed 's/$/.html/' | sed 's/\/.html$/\/index.html/' | sed 's/^.*\///'`
    - cd `echo $SITE_TO_READ_LATER | sed 's/^https:\/\///' | sed 's/$/.html/' | sed 's/\/.html$/\/index.html/' | sed 's/\/[^/]*.html$//'`
    - pandoc -s -r html `echo $SITE_TO_READ_LATER | sed 's/^https:\/\///' | sed 's/$/.html/' | sed 's/\/.html$/\/index.html/' | sed 's/^.*\///'` -o $CI_PROJECT_DIR/readlater.epub
  dependencies:
    - downloadHtml
  artifacts:
    paths:
      - readlater.epub

convertEpubToMobi:
  image: linuxserver/calibre:latest
  stage: convert_epub_to_mobi
  only:
    - web
  script:
    - ebook-convert readlater.epub readlater.mobi
  dependencies:
    - convertPageToEpub
  artifacts:
    paths:
      - readlater.mobi

sendEmailToKindle:
  image: alpine:latest
  stage: send_email_to_kindle
  only:
    - web
  dependencies:
    - convertEpubToMobi
  script:
    - apk add bash coreutils msmtp sed
    - bash -c "sed -i 's/\[MSMTPSERV\]/$(echo \"$MSMTPSERV\")/' mailconfig"
    - bash -c "sed -i 's/\[MSMTPFROM\]/$(echo \"$MSMTPFROM\")/' mailconfig"
    - bash -c "sed -i 's/\[MSMTPUSER\]/$(echo \"$MSMTPUSER\")/' mailconfig"
    - bash -c "sed -i 's/\[MSMTPPASS\]/$(echo \"$MSMTPPASS\")/' mailconfig"
    - cp mailconfig /etc/msmtprc
    - bash -c "sed -i 's/\[MESSAGEIDREPLACE\]/$(date | sha1sum - | awk '{print $1}')11/' readlater.msg"
    - base64 -i readlater.mobi >> readlater.msg
    - echo "--=_[MESSAGEBOUNDARYREPLACE]--" >> readlater.msg
    - bash -c "sed -i 's/\[MESSAGEBOUNDARYREPLACE\]/$(date | sha1sum - | awk '{print $1}')22/' readlater.msg"
    - bash -c "sed -i 's/filename=readlater.mobi/filename=readlater.mobi;\n size=$(ls -l $CI_PROJECT_DIR | grep readlater.mobi | awk '{print $5}')/' readlater.msg"
    - bash -c "sed -i 's/readlater.mobi/$(date | sha1sum - | awk '{print $1}')33.mobi/' readlater.msg"
    - cat readlater.msg | msmtp --account=yourmail $KINDLEEMAIL
  artifacts:
    paths:
      - readlater.msg