Subject: An ebook to read later.
User-Agent: Roundcube Webmail/1.4.11
Message-ID: <[MESSAGEIDREPLACE]@az.id.au>
Content-Type: multipart/mixed;
 boundary="=_[MESSAGEBOUNDARYREPLACE]"

--=_[MESSAGEBOUNDARYREPLACE]
Content-Transfer-Encoding: 7bit
Content-Type: text/plain; charset=US-ASCII;
 format=flowed

An ebook to read later attached.
--=_[MESSAGEBOUNDARYREPLACE]
Content-Transfer-Encoding: base64
Content-Type: application/x-mobipocket-ebook;
 name=readlater.mobi
Content-Disposition: attachment;
 filename=readlater.mobi

